In [ ]:
# Learn how to use NumPy, Pandas, Seaborn , Matplotlib , Plotly , Scikit-Learn , Machine Learning, Tensorflow , and more

In [ ]:
#ch1 Numpy

In [32]:
#python crash course

#data types

#numbers

#strings

#printing
# num = 7
# name = 'andrew'
# print('my number is {one} and my name is {two}, more info {one}'.format(one=num,two=name))
# my number is 7 and my name is andrew, more info 7

#lists

#dictionaries
# d = {'k1':{'innerkey':[1,2,3]}}
# d['k1']['innerkey'][1]
# 2

#booleans

#tuples - items cannot be reassigned like in a list

#sets - only unique elements {1,1,1,2,2,2,3,3,3}
# {1,2,3}
# .add() - like append but for sets

#comparison operators - 1 > 2 false

#if,elif,else statements

#for loops

#while loops

#range() - for x in range(0,5):
# list(range(10))
# [0,1,2,3,4,5,6,7,8,9]

#list comprehensions - create a new list based on the values of an existing list
# x=[1,2,3,4]
# [num**2 for num in x]
# [1, 4, 9, 16]

# x=[1,2,3,4]
# out = [num**2 for num in x]
# out
# [1, 4, 9, 16]

#functions
# def square(num):
#     """
#     THIS IS A DOCSTRING
#     CAN GO MULTIPLE LINES.
#     THIS FUNCTION SQUARES A NUMBER
#     """
#     return num **2

# square(2)
# 4

#map and filter

# seq = [1,2,3,4,5]
# def times2(var):
#     return var*2
# times2(5)
# 10

# if you wanted to take every single element from seq and apply the times2 function,
# you could use a loop and append to a new list but instead you can use map

# seq = [1,2,3,4,5]
# def times2(var):
#     return var*2
# newlist = list(map(times2,seq))
# newlist
# [2, 4, 6, 8, 10]


#instead of completely defining a whole function - using map might be a one time deal - this is where lambda comes into play
#lambda expressions

# def times2(var):
#     return var*2

# this can be written on one line
# def times2(var):return var*2
# a lambda will try to replicate this structure but remove words not needed
# def and return are given values
# t = lambda var:var*2
# t(6)
# 12

# you can use this with map

# seq2=[1,2,3,4,5]
# list(map(lambda num:num*2,seq2))
# [2, 4, 6, 8, 10]

# filter will filter out elements from a sequence
#function that returns boolean values are needed
# seq2=[1,2,3,4,5]
# list(filter(lambda num:num%2==0,seq2))
# returns even numbers in seq
# [2, 4]

#***Map will output the results of all items in a sequence being applied to that function/lambda expression
#***Filter will return the results of the numbers in the sequence that have been applied to that lambda or function expression that checks for a boolean value

#methods
# s = 'hello my name is andrew'
# s.split()
# ['hello', 'my', 'name', 'is', 'andrew']

# tweet = 'go sports #sports'
# tweet.split('#')[1]
# ['go sports ', 'sports']
# 'sports'


# useful methods for dictionaries
# newdict = {'k1':1,'k2':2}

# newdict.keys()
# dict_keys(['k1', 'k2'])

# newdict.items()
# dict_items([('k1', 1), ('k2', 2)])

# newdict.values()
# dict_values([1, 2])


#tuple unpacking
# t1 = [(1,2),(3,4),(5,6)]
# t1[0][0]
# 1

# for item in t1:
#     print(item)
# (1, 2)
# (3, 4)
# (5, 6)

# for a,b in t1:
#     print(a)
# 1
# 3
# 5

1
3
5


In [10]:
#practice
#Create a function that counts the number of times the word "dog" occurs in a string.

def countdog(sent):
    new = sent.split()
    dogcount=0
    for word in new:
        if word == 'dog':
            dogcount += 1
    return dogcount

countdog('dog dog dog cat dog dog')

5

In [11]:
# Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'

seq = ['soup','dog','salad','cat','great']
list(filter(lambda item:item[0]=='s',seq))

['soup', 'salad']

In [ ]:
#NumPy section
#data analysis library

# NumPy is a linear algebra library for python, the reason it is important
#  to data science is that almost all of the libraries in the PyData 
#  Ecosystem rely on numpy as one of their main building blocks

# NumPy arrays are the main way we will use Numpy throughout the course. 
# Numpy arrays essentially come in two flavors: 

# vectors 
# and 
# matrices. 

# Vectors are strictly 1-d arrays and matrices are 2-d 
# (a matrix can still have only one row or colomn.)


In [14]:
# numpy arrays
# vectors and matrices

import numpy as np

my_list = [1,2,3]

arr = np.array(my_list)

arr

array([1, 2, 3])

In [15]:
#if you want matrix - 2d array list of lists
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#creating a numpy array
#similar to pythons range function
#from - to - step size
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros(5)
#returns 1d vector

array([0., 0., 0., 0., 0.])

In [22]:
        #rows,columns
np.zeros((5,5))
# returns 2d matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
# linspace function - turns evenly spaced numbers over a specified interval
#going to take in an argument of how many points you want

            #start - stop - number
            #you want to get 10 EVENLY spaced points BETWEEN 0 and 5
np.linspace(0,5,10)
# returns back a 1 demensional vector of 10 EVENLY spaced points BETWEEN 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
# array([ - one bracket means one demensional
# array([[ = two bracket means two demensional array
# three demensions will have 3 brackets etc

In [25]:
#identity matrix
np.eye(4)

# useful with linear algebra problems
# 2 dimensional square matrix - SAME number of rows is = to the SAME number of columns 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
# numpy has ways of creating arrays of random numbers
np.random.rand(4)
#random samples from a uniform distribution over 0 - 1
# if you want a 1 dimensional array of random numbers random from 0 - 1

array([0.19815499, 0.78298399, 0.72267546, 0.81359062])

In [30]:
#if you want it to be 2 dimensional
#instead of passing in a tuple - pass in the dimensions of the seperate arguments

                #(make 5 rows #sample 3 numbers from 0 - 1)
np.random.rand(5,3)

array([[0.89913149, 0.58657893, 0.18832296],
       [0.05348721, 0.28594569, 0.87219429],
       [0.55794817, 0.77435286, 0.90583638],
       [0.11566235, 0.21297028, 0.13924996],
       [0.90745965, 0.27884058, 0.4179274 ]])

In [32]:
# if you want to return a sample or many samples from the standard normal distribution
# instead of using rand - you can use randn

np.random.randn(2)
#this will return numbers not from a uniform ditribution from 0 - 1 but instead
# from a normal distribution centered around 0

#look up gaussian distribution

array([-0.08899884,  1.53325019])

In [33]:
np.random.randn(4,4)

array([[ 0.94146782,  0.06388578, -2.02805717, -1.49061844],
       [ 0.3204236 ,  0.98464978, -0.37511418,  3.47788607],
       [-1.46815863, -2.55828146,  0.77763494,  0.60496953],
       [-0.25849772, -0.17934867, -0.76283008, -1.63316356]])

In [34]:
#final random method of creating an array is rand int
# returns random integers from a low to a high number
np.random.randint(1,100)
#random int from 1 to 100

28

In [35]:
#if you want multiple random integers
                        #how many
np.random.randint(1,100,3)
#includes 1
#doesn't include 100

array([54, 51, 84])

In [67]:
#useful attributes of an array
#create 2 array objects

arr1=np.arange(25)

ranarr = np.random.randint(0,50,25)

#useful methods to use on arrays
#reshape method
#same data new shape

            #dimensions
arr1.reshape(5,5)
#if the matrix isn't completely filled, you will recieve an error

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
ranarr

array([ 1, 27, 15, 11, 46, 30, 34,  7, 10,  2,  3, 32, 32, 34, 47, 29, 22,
        9, 29, 10, 13, 37, 19, 19, 32])

In [68]:
#call the max value in array
ranarr.max()

47

In [69]:
arr1.min()

0

In [70]:
ranarr

array([ 1, 27, 15, 11, 46, 30, 34,  7, 10,  2,  3, 32, 32, 34, 47, 29, 22,
        9, 29, 10, 13, 37, 19, 19, 32])

In [74]:
#if you want to know at what index value is that max/min number
print(ranarr.argmax(),'\n',ranarr.argmin())
#14 is the location of the max value

14 
 0


In [76]:
#if you want to figure out the shape of a vector
arr1.shape
#indicates that that array is a 1 dimensional vector

(25,)

In [79]:
arr2=np.random.randn(3,3)
arr2

array([[-0.1918129 , -0.20762776,  0.28041738],
       [ 0.43743278,  0.53940329, -0.06285846],
       [-1.86729123, -0.43904174, -0.71737762]])

In [80]:
arr2.shape
#indicates that that array is a 2 dimensional matrix

(3, 3)

In [81]:
arr1.shape

(25,)

In [83]:
newarr = arr1.reshape(5,5)
newarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [84]:
newarr.shape

(5, 5)

In [86]:
#how to figure out data type
newarr.dtype

dtype('int32')

In [89]:
#if you dont want to type out np.random.randn
from numpy.random import randint
randint(2,10)

8

In [ ]:
# np.array(my_list) - uses my list to make a numpy array
# array([1, 2, 3])


# np.arange(x,y,z) - creating a numpy array similar to pythons RANGE function: from x, to y, step size z
# array([ 0,  2,  4,  6,  8, 10])


# np.linspace(x,y,z) - turns evenly spaced numbers over a specified interval - returns back a 1 demensional vector of z EVENLY spaced points BETWEEN x and y
# array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
#        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])


# np.zeros(x) - creates an array of x zeros or any other number after np. ex. 'one'
# array([0., 0., 0., 0., 0.])


# np.ones((x,y)) - creates a matrix of 'ones' x by y 
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])


# np.eye(x) - creates x by x matrix 'square'
# array([[1., 0., 0., 0.],
#        [0., 1., 0., 0.],
#        [0., 0., 1., 0.],
#        [0., 0., 0., 1.]])


# np.random.rand(x) - x amount of random numbers
# array([0.19815499, 0.78298399, 0.72267546, 0.81359062])


# np.random.randn(x,y) x by y amount of random numbers
# array([[0.89913149, 0.58657893, 0.18832296],
#        [0.05348721, 0.28594569, 0.87219429],
#        [0.55794817, 0.77435286, 0.90583638],
#        [0.11566235, 0.21297028, 0.13924996],
#        [0.90745965, 0.27884058, 0.4179274 ]])

# np.random.randint(x,y) - random int between x and y
# 28

# np.random.randint(x,y,z) - z amount random ints between x and y
# array([ 1, 27, 15, 11, 46, 30, 34,  7, 10,  2,  3, 32, 32, 34, 47, 29, 22,
#         9, 29, 10, 13, 37, 19, 19, 32])

# arr.reshape(x,y) - *reshape an array of 25 into 5,5 matrix
# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14],
#        [15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24]])


# arr.max() - finds max in array


# arr.min() - finds min in array


# arr.shape - finds shape of matrices
# (5, 5)

# arr.dtype - finds datatype
# dtype('int32')


In [2]:
# selecting elements or groups of elements from a numpy array

import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr[8]

8

In [93]:
arr[1:5]

array([1, 2, 3, 4])

In [94]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [95]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [96]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [5]:
# numpy arrays differ from a normal python list because of their ability
# to broadcast

arr[0:5] = 100
arr

#broadcast to those 5 digits to be equal to 100

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [13]:
arr
#the original array was also changed, not just the slice

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#data is not copied, it is just a view of the original array
#numpy does this to avoid memory issues with very large arrays

In [16]:
#if you want to make a copy - you can specify
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [18]:
print(arr,'\n',arr_copy)

[99 99 99 99 99 99  6  7  8  9 10] 
 [100 100 100 100 100 100 100 100 100 100 100]


In [21]:
#indexing a 2d array / martix
arr_2d = np.array([[5,6,7],[8,9,10],[11,12,13]])
arr_2d

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [27]:
# 2 formats for grabbing elements from a matrix
#double bracket format
# arr_2d[0][0]
# 5

# arr_2d[2][2]
# 13
    #row -> and column v

#single bracket format * recommended
# arr_2d[1,2]
# 10

In [30]:
#if you want submatrices from this matrix

# array([[ 5,  6,  7],
#        [ 8,  9, 10],
#        [11, 12, 13]])

arr_2d[:2,1:]
#up to but not including 2

# 0
# 1
# ---
# 2

array([[ 6,  7],
       [ 9, 10]])

In [34]:
arr_2d

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [46]:
arr_2d[1:3,0:2]

array([[ 8,  9],
       [11, 12]])

In [50]:
#conditional selection
arrnew = np.arange(1,11)
arrnew
#take this array and combine it with comparison operators
# to get a full boolean array

bool_arr = arrnew %2 == 0,
bool_arr

(array([False,  True, False,  True, False,  True, False,  True, False,
         True]),)

In [52]:
arrnew[bool_arr]
#original array arrnew
# indexing elements from arrnew with True bool values

array([ 2,  4,  6,  8, 10])

In [53]:
#this is how you would simplify that
#conditional selection
arrbool = np.arange(1,11)
arrbool[arrbool%2==0]

array([ 2,  4,  6,  8, 10])

In [56]:
arr_new = np.arange(50).reshape(5,10)
arr_new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [1]:
#numpy operations
#operations with arrays

# array with array
# array with scalars
# universal array functions

import numpy as np

array = np.arange(0,11)
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [2]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
#scalars are a single number that is broadcasted to every element in the array

array + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [5]:
# does not change array values
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
1/0

ZeroDivisionError: division by zero

In [7]:
array / array

C:\Users\brasea\AppData\Local\Temp\ipykernel_14140\3681233016.py:1: RuntimeWarning: invalid value encountered in divide
  array / array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#executed and returned a nan value

In [8]:
1 / array

C:\Users\brasea\AppData\Local\Temp\ipykernel_14140\1508088032.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / array


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
#if you try to devide another number by zero in the array , it will return back infity -inf

In [9]:
# universal array functions - mathmatical operations you can use to perform the operations and broadcast it
# across the entire array 

#square root of every element in array
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [10]:
np.exp(array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [11]:
#for maximum
np.max(array)

10

In [13]:
# OR you can call the max method
array.max()

10

In [12]:
# can do trigonometric functions 
np.sin(array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [15]:
np.log(array)
#-inf for first value

C:\Users\brasea\AppData\Local\Temp\ipykernel_14140\299125506.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
# https://numpy.org/doc/stable/reference/ufuncs.html
# more universal array documentaion