In [ ]:
# Learn how to use NumPy, Pandas, Seaborn , Matplotlib , Plotly , Scikit-Learn , Machine Learning, Tensorflow , and more

In [ ]:
#ch1

In [32]:
#python crash course

#data types

#numbers

#strings

#printing
# num = 7
# name = 'andrew'
# print('my number is {one} and my name is {two}, more info {one}'.format(one=num,two=name))
# my number is 7 and my name is andrew, more info 7

#lists

#dictionaries
# d = {'k1':{'innerkey':[1,2,3]}}
# d['k1']['innerkey'][1]
# 2

#booleans

#tuples - items cannot be reassigned like in a list

#sets - only unique elements {1,1,1,2,2,2,3,3,3}
# {1,2,3}
# .add() - like append but for sets

#comparison operators - 1 > 2 false

#if,elif,else statements

#for loops

#while loops

#range() - for x in range(0,5):
# list(range(10))
# [0,1,2,3,4,5,6,7,8,9]

#list comprehensions - create a new list based on the values of an existing list
# x=[1,2,3,4]
# [num**2 for num in x]
# [1, 4, 9, 16]

# x=[1,2,3,4]
# out = [num**2 for num in x]
# out
# [1, 4, 9, 16]

#functions
# def square(num):
#     """
#     THIS IS A DOCSTRING
#     CAN GO MULTIPLE LINES.
#     THIS FUNCTION SQUARES A NUMBER
#     """
#     return num **2

# square(2)
# 4

#map and filter

# seq = [1,2,3,4,5]
# def times2(var):
#     return var*2
# times2(5)
# 10

# if you wanted to take every single element from seq and apply the times2 function,
# you could use a loop and append to a new list but instead you can use map

# seq = [1,2,3,4,5]
# def times2(var):
#     return var*2
# newlist = list(map(times2,seq))
# newlist
# [2, 4, 6, 8, 10]


#instead of completely defining a whole function - using map might be a one time deal - this is where lambda comes into play
#lambda expressions

# def times2(var):
#     return var*2

# this can be written on one line
# def times2(var):return var*2
# a lambda will try to replicate this structure but remove words not needed
# def and return are given values
# t = lambda var:var*2
# t(6)
# 12

# you can use this with map

# seq2=[1,2,3,4,5]
# list(map(lambda num:num*2,seq2))
# [2, 4, 6, 8, 10]

# filter will filter out elements from a sequence
#function that returns boolean values are needed
# seq2=[1,2,3,4,5]
# list(filter(lambda num:num%2==0,seq2))
# returns even numbers in seq
# [2, 4]

#***Map will output the results of all items in a sequence being applied to that function/lambda expression
#***Filter will return the results of the numbers in the sequence that have been applied to that lambda or function expression that checks for a boolean value

#methods
# s = 'hello my name is andrew'
# s.split()
# ['hello', 'my', 'name', 'is', 'andrew']

# tweet = 'go sports #sports'
# tweet.split('#')[1]
# ['go sports ', 'sports']
# 'sports'


# useful methods for dictionaries
# newdict = {'k1':1,'k2':2}

# newdict.keys()
# dict_keys(['k1', 'k2'])

# newdict.items()
# dict_items([('k1', 1), ('k2', 2)])

# newdict.values()
# dict_values([1, 2])


#tuple unpacking
# t1 = [(1,2),(3,4),(5,6)]
# t1[0][0]
# 1

# for item in t1:
#     print(item)
# (1, 2)
# (3, 4)
# (5, 6)

# for a,b in t1:
#     print(a)
# 1
# 3
# 5

1
3
5


In [10]:
#practice
#Create a function that counts the number of times the word "dog" occurs in a string.

def countdog(sent):
    new = sent.split()
    dogcount=0
    for word in new:
        if word == 'dog':
            dogcount += 1
    return dogcount

countdog('dog dog dog cat dog dog')

5

In [11]:
# Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'

seq = ['soup','dog','salad','cat','great']
list(filter(lambda item:item[0]=='s',seq))

['soup', 'salad']

In [ ]:
#NumPy section
#data analysis library

# NumPy is a linear algebra library for python, the reason it is important
#  to data science is that almost all of the libraries in the PyData 
#  Ecosystem rely on numpy as one of their main building blocks

# NumPy arrays are the main way we will use Numpy throughout the course. 
# Numpy arrays essentially come in two flavors: 

# vectors 
# and 
# matrices. 

# Vectors are strictly 1-d arrays and matrices are 2-d 
# (a matrix can still have only one row or colomn.)


In [14]:
# numpy arrays
# vectors and matrices

import numpy as np

my_list = [1,2,3]

arr = np.array(my_list)

arr

array([1, 2, 3])

In [15]:
#if you want matrix - 2d array list of lists
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#creating a numpy array
#similar to pythons range function
#from - to - step size
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros(5)
#returns 1d vector

array([0., 0., 0., 0., 0.])

In [22]:
        #rows,columns
np.zeros((5,5))
# returns 2d matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
# linspace function - turns evenly spaced numbers over a specified interval
#going to take in an argument of how many points you want

            #start - stop - number
            #you want to get 10 EVENLY spaced points BETWEEN 0 and 5
np.linspace(0,5,10)
# returns back a 1 demensional vector of 10 EVENLY spaced points BETWEEN 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
# array([ - one bracket means one demensional
# array([[ = two bracket means two demensional array
# three demensions will have 3 brackets etc

In [25]:
#identity matrix
np.eye(4)

# useful with linear algebra problems
# 2 dimensional square matrix - SAME number of rows is = to the SAME number of columns 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
# numpy has ways of creating arrays of random numbers
np.random.rand(4)
#random samples from a uniform distribution over 0 - 1
# if you want a 1 dimensional array of random numbers random from 0 - 1

array([0.19815499, 0.78298399, 0.72267546, 0.81359062])

In [30]:
#if you want it to be 2 dimensional
#instead of passing in a tuple - pass in the dimensions of the seperate arguments

                #(make 5 rows #sample 3 numbers from 0 - 1)
np.random.rand(5,3)

array([[0.89913149, 0.58657893, 0.18832296],
       [0.05348721, 0.28594569, 0.87219429],
       [0.55794817, 0.77435286, 0.90583638],
       [0.11566235, 0.21297028, 0.13924996],
       [0.90745965, 0.27884058, 0.4179274 ]])

In [32]:
# if you want to return a sample or many samples from the standard normal distribution
# instead of using rand - you can use randn

np.random.randn(2)
#this will return numbers not from a uniform ditribution from 0 - 1 but instead
# from a normal distribution centered around 0

#look up gaussian distribution

array([-0.08899884,  1.53325019])

In [33]:
np.random.randn(4,4)

array([[ 0.94146782,  0.06388578, -2.02805717, -1.49061844],
       [ 0.3204236 ,  0.98464978, -0.37511418,  3.47788607],
       [-1.46815863, -2.55828146,  0.77763494,  0.60496953],
       [-0.25849772, -0.17934867, -0.76283008, -1.63316356]])