In [ ]:
# Learn how to use NumPy, Pandas, Seaborn , Matplotlib , Plotly , Scikit-Learn , Machine Learning, Tensorflow , and more

In [ ]:
#ch1

In [32]:
#python crash course

#data types

#numbers

#strings

#printing
# num = 7
# name = 'andrew'
# print('my number is {one} and my name is {two}, more info {one}'.format(one=num,two=name))
# my number is 7 and my name is andrew, more info 7

#lists

#dictionaries
# d = {'k1':{'innerkey':[1,2,3]}}
# d['k1']['innerkey'][1]
# 2

#booleans

#tuples - items cannot be reassigned like in a list

#sets - only unique elements {1,1,1,2,2,2,3,3,3}
# {1,2,3}
# .add() - like append but for sets

#comparison operators - 1 > 2 false

#if,elif,else statements

#for loops

#while loops

#range() - for x in range(0,5):
# list(range(10))
# [0,1,2,3,4,5,6,7,8,9]

#list comprehensions - create a new list based on the values of an existing list
# x=[1,2,3,4]
# [num**2 for num in x]
# [1, 4, 9, 16]

# x=[1,2,3,4]
# out = [num**2 for num in x]
# out
# [1, 4, 9, 16]

#functions
# def square(num):
#     """
#     THIS IS A DOCSTRING
#     CAN GO MULTIPLE LINES.
#     THIS FUNCTION SQUARES A NUMBER
#     """
#     return num **2

# square(2)
# 4

#map and filter

# seq = [1,2,3,4,5]
# def times2(var):
#     return var*2
# times2(5)
# 10

# if you wanted to take every single element from seq and apply the times2 function,
# you could use a loop and append to a new list but instead you can use map

# seq = [1,2,3,4,5]
# def times2(var):
#     return var*2
# newlist = list(map(times2,seq))
# newlist
# [2, 4, 6, 8, 10]


#instead of completely defining a whole function - using map might be a one time deal - this is where lambda comes into play
#lambda expressions

# def times2(var):
#     return var*2

# this can be written on one line
# def times2(var):return var*2
# a lambda will try to replicate this structure but remove words not needed
# def and return are given values
# t = lambda var:var*2
# t(6)
# 12

# you can use this with map

# seq2=[1,2,3,4,5]
# list(map(lambda num:num*2,seq2))
# [2, 4, 6, 8, 10]

# filter will filter out elements from a sequence
#function that returns boolean values are needed
# seq2=[1,2,3,4,5]
# list(filter(lambda num:num%2==0,seq2))
# returns even numbers in seq
# [2, 4]

#***Map will output the results of all items in a sequence being applied to that function/lambda expression
#***Filter will return the results of the numbers in the sequence that have been applied to that lambda or function expression that checks for a boolean value

#methods
# s = 'hello my name is andrew'
# s.split()
# ['hello', 'my', 'name', 'is', 'andrew']

# tweet = 'go sports #sports'
# tweet.split('#')[1]
# ['go sports ', 'sports']
# 'sports'


# useful methods for dictionaries
# newdict = {'k1':1,'k2':2}

# newdict.keys()
# dict_keys(['k1', 'k2'])

# newdict.items()
# dict_items([('k1', 1), ('k2', 2)])

# newdict.values()
# dict_values([1, 2])


#tuple unpacking
# t1 = [(1,2),(3,4),(5,6)]
# t1[0][0]
# 1

# for item in t1:
#     print(item)
# (1, 2)
# (3, 4)
# (5, 6)

# for a,b in t1:
#     print(a)
# 1
# 3
# 5

1
3
5


In [10]:
#practice
#Create a function that counts the number of times the word "dog" occurs in a string.

def countdog(sent):
    new = sent.split()
    dogcount=0
    for word in new:
        if word == 'dog':
            dogcount += 1
    return dogcount

countdog('dog dog dog cat dog dog')

5

In [11]:
# Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'

seq = ['soup','dog','salad','cat','great']
list(filter(lambda item:item[0]=='s',seq))

['soup', 'salad']

In [ ]:
#NumPy section
#data analysis library

# NumPy is a linear algebra library for python, the reason it is important
#  to data science is that almost all of the libraries in the PyData 
#  Ecosystem rely on numpy as one of their main building blocks

# NumPy arrays are the main way we will use Numpy throughout the course. 
# Numpy arrays essentially come in two flavors: 

# vectors 
# and 
# matrices. 

# Vectors are strictly 1-d arrays and matrices are 2-d 
# (a matrix can still have only one row or colomn.)


In [14]:
# numpy arrays
# vectors and matrices

import numpy as np

my_list = [1,2,3]

arr = np.array(my_list)

arr

array([1, 2, 3])

In [15]:
#if you want matrix - 2d array list of lists
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#creating a numpy array
#similar to pythons range function
#from - to - step size
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])